version: '3.8'                          # Compose file version
services:
  db:                                  # Service name → becomes a hostname
    image: postgres:15                 # Official Postgres image, pinned to v15
    env_file:
      - .env 
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data across container restarts
    ports:
      - "5432:5432"                    # Expose container’s 5432 on host’s 5432

  tester:
    build: .                   # Build from Dockerfile in current directory
    working_dir: /app
    volumes:
      - .:/app                      # mount your code into the container
    env_file:
      - .env                        # loads POSTGRES_USER, POSTGRES_PASSWORD, etc.
    depends_on:
      - db
    
volumes:
  db_data: {}                           # Named volume for persistent storage
