# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15  # PostgreSQL 15 (stable)
    environment:
      POSTGRES_USER: fastapi_user      # Custom username
      POSTGRES_PASSWORD: Press@3150    # Your password (special chars allowed here)
      POSTGRES_DB: expense_tracker     # Database name
    ports:
      - "5432:5432"                   # Map host port 5432 → container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
volumes:
  postgres_data:  # Named volume (avoids data loss on container restart)