version: '3.8'                          # Compose file version
services:
  db:                                  # Service name → becomes a hostname
    image: postgres:15                 # Official Postgres image, pinned to v15
    env_file:
      - .env 
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data across container restarts
    ports:
      - "5432:5432"                    # Expose container’s 5432 on host’s 5432
volumes:
  db_data: {}                           # Named volume for persistent storage
