version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -e .
      - pip install pytest pytest-asyncio httpx

  pre_build:
    commands:
      - |
        docker run -d --name postgres-ci \
          -e POSTGRES_USER=$POSTGRES_USER \
          -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
          -e POSTGRES_DB=$POSTGRES_DB \
          -p 5432:5432 public.ecr.aws/docker/library/postgres:15
        echo "Waiting for Postgres to be ready…"
        until docker exec postgres-ci pg_isready -U $POSTGRES_USER -d $POSTGRES_DB; do
          sleep 3
        done
        alembic upgrade head

  build:
    commands:
      - pytest -q

artifacts:
  files:
    - '**/*'
  discard-paths: yes
